# @package _global_
defaults:
  - /default
  - _self_
task_name: imputation_pypots
model_id: pypots_multiratio
group_id: 9051
is_training: 1
itr: 5
train_epochs: 300
patience: 30
lradj: type3
data: illness
root_path: ./
data_path: national_illness.csv
features: M
seq_len: 96
label_len: 0
pred_len: 0
enc_in: 7
dec_in: 7
c_out: 7
test_scenarios:
- name: point_missing_only
  patterns:
  - type: mcar
    rates:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
- name: sensor_failure
  patterns:
  - type: mcar
    rate: 0.05
  - type: sequence
    rate: 0.0015
    seq_len:
      range:
      - 24
      - 96
state: NotStarted
model: TimesNet
model_params:
  n_layers: 2
  top_k: 3
  d_model: 64
  d_ffn: 64
  n_kernels: 6
  dropout: 0.1
  apply_nonstationary_norm: true
batch_size: 16
learning_rate: 0.001
mit_rate: 0.4
MIT_weight: 1.0
ORT_weight: 0.0
base_loss: MSE
des: PyPOTS_illness_TimesNet
