task_name: long_term_forecast
is_training: 1
model_id: test
model: Autoformer
state: Not Started
data: ETTm1
root_path: ./data/ETT/
data_path: ETTh1.csv
features: M
target: OT
freq: h
checkpoints: ./lab/checkpoints/
seq_len: 96
label_len: 48
pred_len: 96
seasonal_patterns: Monthly
inverse: false
mask_rate: 0.25
anomaly_ratio: 0.25
expand: 2
d_conv: 4
top_k: 5
num_kernels: 6
enc_in: 7
dec_in: 7
c_out: 7
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 1
distil: true
dropout: 0.1
embed: timeF
activation: gelu
channel_independence: 1
decomp_method: moving_avg
use_norm: 1
down_sampling_layers: 0
down_sampling_window: 1
down_sampling_method: null
seg_len: 48
num_workers: 5
itr: 5
train_epochs: 300
batch_size: 32
patience: 30
learning_rate: 0.0001
des: test
loss: MSE
lradj: type1
use_amp: false
use_gpu: true
gpu: 0
gpu_type: cuda
use_multi_gpu: false
devices: 0,1,2,3
p_hidden_dims:
- 128
- 128
p_hidden_layers: 2
use_dtw: false
augmentation_ratio: 0
seed: 2
jitter: false
scaling: false
permutation: false
randompermutation: false
magwarp: false
timewarp: false
windowslice: false
windowwarp: false
rotation: false
spawner: false
dtwwarp: false
shapedtwwarp: false
wdba: false
discdtw: false
discsdtw: false
extra_tag: ''
patch_len: 16
m4_id: 0
group_id: 0
exp_type: baseline
accumulate_grad_batches: 1
patch_size: 4
patch_stride: 4
downsample_ratio: 2
positional_encoding: true
kernel_size_large: 51
kernel_size_small: 5
qkv_bias: true
ffn_ratio: 4
series_decomp: false
pad_only_left: false
revin: true
affine: true
subtract_last: false
optimizer: adam
use_model_compile: false
